name: Build binary and docker image

on:
  push:
    tags:
    - v*
  workflow_dispatch:


env:
  APP_NAME: loongcollector-alpha
  DOCKERHUB_REPO: registry.cn-hangzhou.aliyuncs.com/kindlingx/loongcollector-alpha

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
        - os: ubuntu-latest
          arch: amd64
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Set custom submodule URL and fetch
      run: |
        SUBMODULE_PATH="core/_thirdparty/coolbpf"
        git config submodule.$SUBMODULE_PATH.url "https://github.com/aliyun/coolbpf.git"
        git submodule update --init
        cd $SUBMODULE_PATH
        echo "Current commit: $(git rev-parse HEAD)"

    - name: Generate App Version
      run: |
        TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
        if [ -n "$TAG" ]; then
          echo "APP_VERSION=$TAG" >> $GITHUB_ENV
        else
          BRANCH=$(git rev-parse --abbrev-ref HEAD | sed 's#[^a-zA-Z0-9._-]#-#g')
          COMMIT=$(git rev-parse --short HEAD)
          echo "APP_VERSION=${BRANCH}-${COMMIT}" >> $GITHUB_ENV
        fi

    - name: Build binary
      env:
        BUILD_LOGTAIL_UT: OFF
        ENABLE_COMPATIBLE_MODE: ON
        ENABLE_STATIC_LINK_CRT: ON
        WITHOUTGDB: ON
        MAKE_JOBS: 16
      run: |
        VERSION=${{ env.APP_VERSION }} make dist

    # - name: Upload to OSS
    #   env:
    #     OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
    #     OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
    #     OSS_BUCKET: apo-oss
    #     OSS_ENDPOINT: https://oss-cn-hangzhou.aliyuncs.com/
    #   run: |
    #     curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
    #     sudo ossutil config -e $OSS_ENDPOINT -i $OSS_ACCESS_KEY_ID -k $OSS_ACCESS_KEY_SECRET -L CH -c /root/.ossutilconfig
    #     sudo ossutil cp dist/ilogtail-${{ env.APP_VERSION }}.linux-${{ matrix.arch }}.tar.gz oss://$OSS_BUCKET/ilogtail-${{ env.APP_VERSION }}.linux-${{ matrix.arch }}.tar.gz

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build docker image and push (AMD64)
      if: matrix.arch == 'amd64'
      run: |
        VERSION=${{ env.APP_VERSION }} DOCKER_REPOSITORY=${{ env.DOCKERHUB_REPO }} make docker
        docker push ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}

    # - name: Build docker image and push (ARM64)
    #   if: matrix.arch == 'arm64'
    #   run: |
    #     VERSION=${{ env.APP_VERSION }} DOCKER_REPOSITORY=${{ env.DOCKERHUB_REPO }} make docker
    #     docker tag ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }} ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}-arm64
    #     docker push ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}-arm64
